//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeWorkFishingElite
{
    using System;
    using System.Collections.Generic;
    
    public partial class fishing_asset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fishing_asset()
        {
            this.fish_status = new HashSet<fish_status>();
            this.fishing_tourists = new HashSet<fishing_tourists>();
        }
    
        public int id { get; set; }
        public System.DateTime created_at { get; set; }
        public string title { get; set; }
        public int category_id { get; set; }
        public decimal catch_cost_per { get; set; }
        public int count_of_individuals { get; set; }
        public string description { get; set; }
    
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fish_status> fish_status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fishing_tourists> fishing_tourists { get; set; }
    }
}
