//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeWorkFishingEliteTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class fishing_tourists
    {
        public int id { get; set; }
        public int fishing_asset_id { get; set; }
        public System.DateTime fishing_data { get; set; }
        public int fishing_result { get; set; }
        public int employee_id { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual fishing_asset fishing_asset { get; set; }
    }
}
