//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeWorkFishingEliteTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FishingEliteEntities : DbContext
    {
        public FishingEliteEntities()
            : base("name=FishingEliteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> category { get; set; }
        public virtual DbSet<employee> employee { get; set; }
        public virtual DbSet<fish_status> fish_status { get; set; }
        public virtual DbSet<fishing_asset> fishing_asset { get; set; }
        public virtual DbSet<fishing_tourists> fishing_tourists { get; set; }
        public virtual DbSet<responsbilities> responsbilities { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
