//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeWorkFishingEliteTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class responsbilities
    {
        public int id { get; set; }
        public int employee_id { get; set; }
        public int role_id { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual role role { get; set; }
    }
}
